services:
  ryu:
    build:
      context: .
      dockerfile: Dockerfile.ryu
    container_name: sdn-ryu
    ports:
      - "6653:6653"
      - "8080:8080"

  exporter:
    build:
      context: .
      dockerfile: Dockerfile.exporter
    container_name: sdn-exporter
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus
    container_name: sdn-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - exporter

  grafana:
    image: grafana/grafana
    container_name: sdn-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards